# Generated by Django 5.0.14 on 2026-07-19 18:12

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_seed_builtin_admin_role'),
        ('dropoff', '0002_dropoffpoint_managers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(max_length=200)),
                ('applicant_email', models.EmailField(max_length=254)),
                ('applicant_phone', models.CharField(blank=True, max_length=32)),
                ('organization_name', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField(blank=True)),
                ('proposed_dropoff_name', models.CharField(blank=True, max_length=200)),
                ('proposed_dropoff_address', models.CharField(blank=True, max_length=300)),
                ('proposed_location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('email_verified_at', models.DateTimeField(blank=True, null=True)),
                ('reviewers_notified_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applicant_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_applications', to=settings.AUTH_USER_MODEL)),
                ('created_dropoff_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dropoff.dropoffpoint')),
                ('granted_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.adminrole')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='partners_pa_status_62d450_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='partnerapplication',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('applicant_email',), name='one_pending_application_per_email'),
        ),
    ]
