# Generated by Django 5.0.14 on 2026-07-21 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_seed_builtin_admin_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='include_in_leaderboard',
            field=models.BooleanField(default=True),
        ),
    ]
