# Generated by Django 5.0.14 on 2026-07-21 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_include_in_leaderboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedDonor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blurb', models.TextField(blank=True)),
                ('featured_from', models.DateTimeField()),
                ('featured_until', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_donor_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-featured_from'],
                'indexes': [models.Index(fields=['featured_from', 'featured_until'], name='accounts_fe_feature_46fdb5_idx')],
            },
        ),
    ]
