# Generated by Django 5.0.14 on 2026-07-12 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('target_type', models.CharField(max_length=32)),
                ('target_id', models.PositiveIntegerField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['target_type', 'target_id'], name='moderation__target__f4e8ea_idx'), models.Index(fields=['action'], name='moderation__action_129b8e_idx')],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('listing', 'Listing'), ('user', 'User')], max_length=16)),
                ('target_id', models.PositiveIntegerField()),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('inappropriate', 'Inappropriate'), ('misrepresented', 'Misrepresented'), ('no_show', 'No show'), ('other', 'Other')], max_length=32)),
                ('detail', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='open', max_length=16)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_filed', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_resolved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='moderation__status_3fc7e7_idx'), models.Index(fields=['reason'], name='moderation__reason_460c2e_idx'), models.Index(fields=['target_type', 'target_id'], name='moderation__target__dc17d8_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('reporter', 'target_type', 'target_id'), name='one_open_report_per_reporter_per_target'),
        ),
    ]
