# Generated by Django 5.0.14 on 2026-07-12 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dropoff', '0001_initial'),
        ('listings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No show')], default='scheduled', max_length=16)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donor_exchanges', to=settings.AUTH_USER_MODEL)),
                ('dropoff_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exchanges', to='dropoff.dropoffpoint')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchanges', to='listings.listing')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_exchanges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['status'], name='exchanges_e_status_13a4f2_idx'), models.Index(fields=['donor'], name='exchanges_e_donor_i_3f66e2_idx'), models.Index(fields=['recipient'], name='exchanges_e_recipie_fa460b_idx'), models.Index(fields=['scheduled_at'], name='exchanges_e_schedul_746ec7_idx')],
            },
        ),
    ]
