# Generated by Django 5.0.14 on 2026-07-19 12:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropoff', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dropoffpoint',
            name='managers',
            field=models.ManyToManyField(blank=True, related_name='managed_dropoff_points', to=settings.AUTH_USER_MODEL),
        ),
    ]
