# Generated by Django 5.0.14 on 2026-07-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImpactStatsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_listings', models.PositiveIntegerField(default=0)),
                ('total_exchanges_completed', models.PositiveIntegerField(default=0)),
                ('total_active_donors', models.PositiveIntegerField(default=0)),
                ('total_active_recipients', models.PositiveIntegerField(default=0)),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-computed_at'],
                'get_latest_by': 'computed_at',
            },
        ),
    ]
