# Generated by Django 5.0.14 on 2026-07-19 07:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('request_received', 'New request received'), ('request_accepted', 'Request accepted'), ('request_declined', 'Request declined'), ('exchange_scheduled', 'Exchange scheduled'), ('exchange_completed', 'Exchange completed'), ('exchange_reminder', 'Exchange reminder'), ('report_resolved', 'Your report was resolved'), ('partner_application_ready', 'Application ready for review'), ('partner_application_approved', 'Application approved'), ('partner_application_rejected', 'Application rejected'), ('role_assigned', 'Your admin role changed'), ('system', 'System notification')], max_length=32)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('target_type', models.CharField(blank=True, max_length=32)),
                ('target_id', models.PositiveIntegerField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx')],
            },
        ),
    ]
